server:
  port: 9394

spring:
  kafka:
    bootstrap-servers: 111.229.66.196:9092
    consumer:
      # 默认值，当消息不存在时，从最早的消息开始消费
      auto-offset-reset: earliest
      # 关闭自动提交
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 手动提交，配合关闭自动提交使用
      ack-mode: manual
  # 多数据源配置
  datasource:
    dynamic:
      # 设置默认的数据源
      primary: clickhouse
      # 严格模式，如果找不到数据源，则报错
      strict: false
      druid: # 以下是支持的全局默认值，每个库还可重新设置独立参数
        initial-size: 5
        min-idle: 5
        max-active: 10
        max-wait: 5000
        validation-query: select 1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: false
      datasource:
        clickhouse:
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:clickhouse://111.229.66.196:8123/default
          username: default
          password: password
          druid: # 以下是单独每个库的设置，默认会使用全局的配置
            initial-size: 10
            min-idle: 10
            max-active: 20
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://111.229.66.196:3306/ttms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
          username: root
          password: password
          druid: # 以下是单独每个库的设置，默认会使用全局的配置
            initial-size: 3
            min-idle: 3
            max-active: 10
    # druid监控配置，需要引入druid-spring-boot-starter依赖而非druid依赖，否则不生效
    # 页面地址：http://127.0.0.1:9394/druid/sql.html
    druid:
      # 用于采集web-jdbc关联监控的数据
      webStatFilter:
        enabled: true
      # 用于展示Druid的统计信息（提供监控信息展示的html页面+提供监控信息的JSON API）
      statViewServlet:
        enabled: true
        # 设置ip白名单（逗号隔开），不填则允许所有访问
        allow:
        # ip黑名单（优先于allow）
        deny:
        # 监控页面的url
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: zxb
        login-password: zxb123
      # 监控数据过滤器
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          # 慢SQL标准，单位毫秒
          slow-sql-millis: 1000
          # 统计SQL合并执行，合并后执行一次
          merge-sql: true
        # SQL防火墙
        wall:
          config:
            # 是否允许一次执行多条语句，默认关闭
            multi-statement-allow: true

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false